import 'jsr:@supabase/functions-js/edge-runtime.d.ts'
import { corsHeaders } from '../_shared/cors.ts'

Deno.serve(async (req: Request) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders })
  }

  try {
    const body = await req.json().catch(() => ({}))
    const region = body.region || 'brasil'

    const geminiKey = Deno.env.get('GEMINI_API_KEY')

    // Mock fallback if no API key is provided
    if (!geminiKey) {
      const mockData = {
        suggestions: [
          {
            name: 'Cessna 152',
            model: 'C152',
            image_url:
              'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Cessna.152.g-bgao.arp.jpg/800px-Cessna.152.g-bgao.arp.jpg',
            summary:
              'O Cessna 152 é uma das aeronaves de instrução mais populares do mundo. Lançado em 1977, possui motor Lycoming O-235 e acomoda dois ocupantes. Sua confiabilidade e características de voo dóceis o tornam o treinador primário padrão em muitas escolas.',
            performance_table: {
              max_speed: '149 KIAS',
              range: '415 nm',
              max_weight: '1670 lbs',
              service_ceiling: '14700 ft',
            },
            performance_graph: {
              type: 'bar',
              data: [
                { label: 'Vne', value: 149 },
                { label: 'Vno', value: 111 },
                { label: 'Va', value: 104 },
              ],
            },
          },
          {
            name: 'Piper Cherokee PA-28',
            model: 'PA-28-140',
            image_url:
              'https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Piper_PA-28-161_Cherokee_Warrior_II_OO-BZZ.jpg/800px-Piper_PA-28-161_Cherokee_Warrior_II_OO-BZZ.jpg',
            summary:
              'O Piper Cherokee é um monomotor de asa baixa amplamente utilizado em instrução. O modelo 140 é especialmente dócil e estável, excelente para treinamento básico e voos de navegação em condições visuais.',
            performance_table: {
              max_speed: '142 KIAS',
              range: '465 nm',
              max_weight: '2150 lbs',
              service_ceiling: '14300 ft',
            },
            performance_graph: {
              type: 'bar',
              data: [
                { label: 'Vne', value: 142 },
                { label: 'Vno', value: 108 },
                { label: 'Va', value: 89 },
              ],
            },
          },
        ],
      }
      return new Response(JSON.stringify(mockData), {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      })
    }

    const prompt = `Liste 10 aeronaves mais utilizadas em voos de instrução em ${region}. Para cada uma, forneça: nome, modelo, imagem URL (busque em commons.wikimedia.org ou similar), resumo de 500 caracteres máximo, tabela de performance (velocidade máxima, autonomia, peso máximo, teto de serviço), e gráfico de performance em JSON (tipo: 'bar', dados: velocidades comparadas). Retorne em JSON estruturado no formato exato a seguir:
{
  "suggestions": [
    {
      "name": "Nome da Aeronave",
      "model": "Modelo",
      "image_url": "URL da imagem",
      "summary": "Resumo curto...",
      "performance_table": {
        "max_speed": "Valor",
        "range": "Valor",
        "max_weight": "Valor",
        "service_ceiling": "Valor"
      },
      "performance_graph": {
        "type": "bar",
        "data": [
          { "label": "Vne", "value": 150 },
          { "label": "Vno", "value": 110 }
        ]
      }
    }
  ]
}
Mantenha a resposta concisa para respeitar o limite de contexto de 5000 caracteres.`

    const controller = new AbortController()
    const timeoutId = setTimeout(() => controller.abort(), 30000)

    const response = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${geminiKey}`,
      {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          contents: [{ parts: [{ text: prompt }] }],
          generationConfig: {
            responseMimeType: 'application/json',
            temperature: 0.7,
            maxOutputTokens: 2500, // Helping to enforce context size limits
          },
        }),
        signal: controller.signal,
      },
    )

    clearTimeout(timeoutId)

    if (!response.ok) {
      const errorText = await response.text()
      throw new Error(`Gemini API error: ${errorText}`)
    }

    const data = await response.json()
    const content = data.candidates?.[0]?.content?.parts?.[0]?.text

    if (!content) {
      throw new Error('No content generated by Gemini')
    }

    let parsedData
    try {
      parsedData = JSON.parse(content)
    } catch (e) {
      const cleanContent = content
        .replace(/```json/g, '')
        .replace(/```/g, '')
        .trim()
      parsedData = JSON.parse(cleanContent)
    }

    return new Response(JSON.stringify(parsedData), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    })
  } catch (error: any) {
    if (error.name === 'AbortError') {
      return new Response(JSON.stringify({ error: 'Request timeout (30s limit exceeded)' }), {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 408,
      })
    }
    return new Response(JSON.stringify({ error: error.message }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      status: 400,
    })
  }
})
