import 'jsr:@supabase/functions-js/edge-runtime.d.ts'
import { corsHeaders } from '../_shared/cors.ts'

Deno.serve(async (req: Request) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders })
  }

  try {
    const body = await req.json().catch(() => ({}))
    const region = body.region || 'brasil'
    
    const geminiKey = Deno.env.get('Default Gemini API Key')

    const prompt = `Liste 3 aeronaves mais utilizadas em voos de instrução em ${region}. Para cada uma, forneça: nome, modelo, imagem URL (busque em commons.wikimedia.org ou similar), resumo de 500 caracteres máximo, tabela de performance (velocidade máxima, autonomia, peso máximo, teto de serviço), e gráfico de performance em JSON (tipo: 'bar', dados: velocidades comparadas). Retorne em JSON estruturado no formato exato a seguir:
{
  "suggestions": [
    {
      "name": "Nome da Aeronave",
      "model": "Modelo",
      "image_url": "URL da imagem",
      "summary": "Resumo curto...",
      "performance_table": {
        "max_speed": "Valor",
        "range": "Valor",
        "max_weight": "Valor",
        "service_ceiling": "Valor"
      },
      "performance_graph": {
        "type": "bar",
        "data": [
          { "label": "Vne", "value": 150 },
          { "label": "Vno", "value": 110 }
        ]
      }
    }
  ]
}
Mantenha a resposta concisa para respeitar o limite de contexto de 5000 caracteres.`

    const controller = new AbortController()
    const timeoutId = setTimeout(() => controller.abort(), 30000)

    const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=${geminiKey}`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        contents: [{ parts: [{ text: prompt }] }],
        generationConfig: {
          responseMimeType: "application/json",
          temperature: 0.7,
          maxOutputTokens: 2500 // Helping to enforce context size limits
        }
      }),
      signal: controller.signal
    })

    clearTimeout(timeoutId)

    if (!response.ok) {
      const errorText = await response.text()
      throw new Error(`Gemini API error: ${errorText}`)
    }

    const data = await response.json()
    const content = data.candidates?.[0]?.content?.parts?.[0]?.text
    
    if (!content) {
      throw new Error('No content generated by Gemini')
    }

    let parsedData
    try {
      parsedData = JSON.parse(content)
    } catch (e) {
      const cleanContent = content.replace(/```json/g, '').replace(/```/g, '').trim()
      parsedData = JSON.parse(cleanContent)
    }

    return new Response(JSON.stringify(parsedData), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    })

  } catch (error: any) {
    if (error.name === 'AbortError') {
      return new Response(JSON.stringify({ error: 'Request timeout (30s limit exceeded)' }), {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 408,
      })
    }
    return new Response(JSON.stringify({ error: error.message }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      status: 400,
    })
  }
})
